import os
import json
import time
import uuid
import threading
from datetime import datetime
from typing import List, Dict, Any, Optional
import numpy as np
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
import pickle
import cv2
import logging
from db.identity_groups import identity_group_manager
from db.face_landmarks import face_landmark_detector

logger = logging.getLogger(__name__)

class JSONTrainingManager:
    """
    Training manager that works with JSON-based identity groups
    This uses actual face embeddings generated by dlib for training a face recognition model
    """
    
    def __init__(self):
        """Initialize the JSON training manager"""
        self.base_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "static")
        self.models_dir = os.path.join(self.base_dir, "models")
        self.jobs_dir = os.path.join(self.base_dir, "training_jobs")
        self.faces_dir = os.path.join(self.base_dir, "faces")
        
        os.makedirs(self.models_dir, exist_ok=True)
        os.makedirs(self.jobs_dir, exist_ok=True)
        
        # In-memory job tracking
        self.jobs = {}
        
    def start_training(self, group_ids: List[str], include_all: bool = False) -> str:
        """Create a new training job for the specified groups"""
        job_id = str(uuid.uuid4())
        
        # If include_all is true, get all group IDs
        if include_all:
            group_ids = list(identity_group_manager.identities.get('groups', {}).keys())
        
        # Create job record
        self.jobs[job_id] = {
            'id': job_id,
            'status': 'queued',
            'progress': 0,
            'created_at': datetime.now().isoformat(),
            'updated_at': datetime.now().isoformat(),
            'group_ids': group_ids,
            'message': 'Training job queued',
            'error': None
        }
        
        # Start training in background thread
        thread = threading.Thread(target=self._train_model, args=(job_id,))
        thread.daemon = True
        thread.start()
        
        return job_id
        
    def get_job_status(self, job_id: str) -> Optional[Dict[str, Any]]:
        """Get status of a training job"""
        return self.jobs.get(job_id)
        
    def _train_model(self, job_id: str):
        """Train the face recognition model using real embeddings"""
        try:
            job = self.jobs.get(job_id)
            if not job:
                logger.error(f"Job {job_id} not found")
                return
                
            group_ids = job.get('group_ids', [])
            logger.info(f"Starting training with {len(group_ids)} selected groups")
            
            # Update job status
            job['status'] = 'processing'
            job['progress'] = 10
            job['message'] = f'Processing {len(group_ids)} groups'
            job['updated_at'] = datetime.now().isoformat()
            
            embeddings = []
            labels = []
            groups_with_embeddings = 0
            groups_without_embeddings = 0
            faces_processed = 0
            faces_with_embeddings = 0
            
            # Get all identity groups
            all_groups = identity_group_manager.identities.get('groups', {})
            
            for i, group_id in enumerate(group_ids):
                progress = 10 + (70 * i // len(group_ids))
                job['progress'] = progress
                job['message'] = f'Processing group {group_id} ({i+1}/{len(group_ids)})'
                job['updated_at'] = datetime.now().isoformat()
                
                group_data = all_groups.get(group_id)
                if not group_data:
                    logger.warning(f"Group {group_id} not found")
                    continue
                
                group_embeddings = []
                face_ids = group_data.get('face_ids', [])
                
                for face_id in face_ids:
                    faces_processed += 1
                    face_path = os.path.join(self.faces_dir, f"{face_id}.jpg")
                    
                    if os.path.exists(face_path):
                        try:
                            # Load face image
                            img = cv2.imread(face_path)
                            if img is not None:
                                # Get embedding using dlib
                                embedding = face_landmark_detector.get_face_embedding(img)
                                if embedding is not None and len(embedding) == 128:
                                    group_embeddings.append(embedding)
                                    faces_with_embeddings += 1
                                else:
                                    logger.warning(f"Failed to get embedding for face {face_id}")
                            else:
                                logger.warning(f"Failed to load image for face {face_id}")
                        except Exception as e:
                            logger.error(f"Error processing face {face_id}: {e}")
                    else:
                        logger.warning(f"Face image not found: {face_path}")
                
                if group_embeddings:
                    # Add all embeddings for this identity
                    embeddings.extend(group_embeddings)
                    labels.extend([group_id] * len(group_embeddings))
                    groups_with_embeddings += 1
                    logger.info(f"Group {group_id}: {len(group_embeddings)} embeddings from {len(face_ids)} faces")
                else:
                    groups_without_embeddings += 1
                    logger.warning(f"Group {group_id}: No valid embeddings from {len(face_ids)} faces")
            
            # Log summary
            logger.info(f"Training summary:")
            logger.info(f"  - Groups requested: {len(group_ids)}")
            logger.info(f"  - Groups with embeddings: {groups_with_embeddings}")
            logger.info(f"  - Groups without embeddings: {groups_without_embeddings}")
            logger.info(f"  - Total faces processed: {faces_processed}")
            logger.info(f"  - Faces with embeddings: {faces_with_embeddings}")
            logger.info(f"  - Total embeddings collected: {len(embeddings)}")
            logger.info(f"  - Unique identities: {len(set(labels))}")
            
            if not embeddings:
                raise Exception(f"No face embeddings found for training. Processed {faces_processed} faces from {len(group_ids)} groups.")
            
            # Update status
            job['progress'] = 80
            job['message'] = f'Training model with {len(embeddings)} embeddings'
            job['updated_at'] = datetime.now().isoformat()
            
            # Convert to numpy arrays
            X = np.array(embeddings)
            y = np.array(labels)
            
            # Normalize embeddings
            scaler = StandardScaler()
            X_scaled = scaler.fit_transform(X)
            
            # Train SVM classifier
            classifier = SVC(kernel='rbf', probability=True, C=1.0, gamma='auto')
            classifier.fit(X_scaled, y)
            
            # Update status
            job['progress'] = 90
            job['message'] = 'Saving model'
            job['updated_at'] = datetime.now().isoformat()
            
            # Save the model and scaler
            model_filename = f"face_recognition_model_{job_id}.pkl"
            model_path = os.path.join(self.models_dir, model_filename)
            
            with open(model_path, 'wb') as f:
                pickle.dump({
                    'classifier': classifier,
                    'scaler': scaler,
                    'labels': list(set(labels)),
                    'embedding_count': len(embeddings),
                    'created_at': datetime.now().isoformat(),
                    'job_id': job_id,
                    'summary': {
                        'groups_requested': len(group_ids),
                        'groups_with_embeddings': groups_with_embeddings,
                        'faces_processed': faces_processed,
                        'faces_with_embeddings': faces_with_embeddings
                    }
                }, f)
                
            # Save as the latest model
            latest_model_path = os.path.join(self.models_dir, "latest_model.pkl")
            with open(latest_model_path, 'wb') as f:
                pickle.dump({
                    'classifier': classifier,
                    'scaler': scaler,
                    'labels': list(set(labels)),
                    'embedding_count': len(embeddings),
                    'created_at': datetime.now().isoformat(),
                    'job_id': job_id,
                    'summary': {
                        'groups_requested': len(group_ids),
                        'groups_with_embeddings': groups_with_embeddings,
                        'faces_processed': faces_processed,
                        'faces_with_embeddings': faces_with_embeddings
                    }
                }, f)
                
            # Update job status to completed
            job['status'] = 'completed'
            job['progress'] = 100
            job['message'] = f'Training completed successfully. Model trained on {len(embeddings)} faces from {len(set(labels))} identities.'
            job['model_path'] = model_path
            job['updated_at'] = datetime.now().isoformat()
            
            logger.info(f"Training job {job_id} completed successfully")
            
        except Exception as e:
            logger.error(f"Error training model for job {job_id}: {str(e)}")
            job['status'] = 'failed'
            job['progress'] = 0
            job['message'] = 'Training failed'
            job['error'] = str(e)
            job['updated_at'] = datetime.now().isoformat()

# Create singleton instance
json_training_manager = JSONTrainingManager()